---
- hosts: all
  become: yes  # Thực hiện với quyền root
  tasks:
    - name: Check payload value and clear path value
      when: ansible_eda.event.payload.clear_path is defined
      ansible.builtin.file:
        path: "{{ ansible_eda.event.payload.clear_path }}" 
        state: absent