---
- name: Get disk information
  hosts: all
  tasks:
    - name: Get information about disks using lsblk
      command: lsblk -o NAME,SIZE,TYPE,MOUNTPOINT
      register: disk_info

    - name: Print disk information
      debug:
        var: disk_info.stdout_lines