---
- name: Gather disk information
  hosts: all
  tasks:
    - name: Gather all facts
      setup:
        gather_subset:
          - hardware

    - name: Print disk information
      debug:
        var: ansible_devices  # In ra thông tin ổ đĩa